jobs:
  main:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Get Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./check/action

name: Run

on:
  schedule:
    - cron: "55 */3 * * *"
